#!/bin/sh

REL_PATH=$PHASE_ROOT/project/work/doc/qc/sp
TODO_DIR=todo
FIXED_DIR=fixed
SIGNEDOFF_DIR=signedoff

echo
echo -----------------------------------
echo PHASE SPR Tracking System V00.03.00
echo EditSpr
echo -----------------------------------
echo

umask 002
if test $1
then
   REL_NAME=$1
else
   echo "Usage: EditSpr <VERSION>"
   exit 1
fi

# check if the release directory exists
if test -d $REL_PATH/$REL_NAME
then
   # Change to to do directory
   cd $REL_PATH/$REL_NAME/$TODO_DIR
   echo "TODO SPRs..."
   ls PHASE_*
   echo -n "Enter SPR name: ";read READ_SPR_FILE_NAME
   SPR_FILE_NAME=`echo $READ_SPR_FILE_NAME | awk '{printf($1)}' `
else
   echo SPR tree for release  $REL_NAME does not exist.
   echo "Exiting EditSpr";
   exit 1;
fi

if test $SPR_FILE_NAME
then
   TODO_SPR=$SPR_FILE_NAME
   if test -f $TODO_SPR
   then
      if test -f SCCS/p.$TODO_SPR
      then
         echo SPR $SPR_FILE_NAME may in use by another person
         exit 1;
      else
         echo "editing  $TODO_SPR ...."
         sccs edit -s $TODO_SPR
      fi
   else
      echo SPR $SPR_FILE_NAME does not exist.
      exit 1;
   fi
else
   echo "No SPR specified"
   exit 1
fi

# edit the file
textedit $TODO_SPR

# Replace in SCCS
sccs delget -s -y"EditSpr" $TODO_SPR

# Cleanup
if test -f $TODO_SPR%
then
   rm $TODO_SPR%
fi


# Mail updated SPR

echo "~c `whoami`" | cat - $TODO_SPR | mail -s "$REL_NAME $TODO_SPR" s3phase


