#!/bin/sh

REL_PATH=$PHASE_ROOT/project/work/doc/qc/sp
TODO_DIR=todo
FIXED_DIR=fixed
SIGNEDOFF_DIR=signedoff

echo 
echo -----------------------------------
echo PHASE SPR Tracking System V00.03.00
echo FixSpr
echo -----------------------------------
echo 

umask 002
if test $1
then
      REL_NAME=$1
else
      echo "Usage: FixSpr <VERSION>"
      exit 1
fi

# check if the release directory exists
if test -d $REL_PATH/$REL_NAME
then
        echo "TODO SPRs..."
        cd $REL_PATH/$REL_NAME/$TODO_DIR
        ls PHASE_*         
        echo -n "Enter SPR name: ";read READ_SPR_FILE_NAME
        SPR_FILE_NAME=`echo $READ_SPR_FILE_NAME | awk '{printf($1)}' `
else
        echo SPR tree for release  $REL_NAME does not exist.
        echo "Exiting FixSpr";
        exit 1;
fi

TODO_SPR=$SPR_FILE_NAME
FIXED_SPR=$SPR_FILE_NAME

if test $SPR_FILE_NAME
then
   if test -f $TODO_SPR
   then
      if test -f SCCS/p.$TODO_SPR
      then
         echo SPR $SPR_FILE_NAME may be inuse by someone else.
         exit 1;
      else
         sccs edit -s $TODO_SPR
         sccs delta -s -y"Changing Status to Fixed" $TODO_SPR
      fi
   else
      echo SPR $SPR_FILE_NAME does not exist.
      exit 1;
   fi
else
   echo "No SPR specified"
   exit 1
fi

cd $REL_PATH/$REL_NAME/$FIXED_DIR
sccs edit -s -r2 $TODO_SPR

echo ""                                                                                >> $FIXED_SPR
echo "------------------------------------------------------------------------------"  >> $FIXED_SPR
echo ""                                                                                >> $FIXED_SPR
echo "Fixed By            : "                                                       >> $FIXED_SPR
echo ""                                                                                >> $FIXED_SPR
echo -n "Date                : "                                                       >> $FIXED_SPR
date '+%d/%m/%y : %H:%M' >> $FIXED_SPR
echo ""                                                                                >> $FIXED_SPR
echo "Problem Resolution  : "                                                          >> $FIXED_SPR
echo ""	                                                                               >> $FIXED_SPR
echo ""                                                                                >> $FIXED_SPR
echo "------------------------------------------------------------------------------"  >> $FIXED_SPR

# edit the file
textedit $FIXED_SPR

sccs delget -s -y"Fixed" $FIXED_SPR

if test -f $FIXED_SPR%
then
   rm $FIXED_SPR%
fi
