#!/bin/sh

REL_PATH=$PHASE_ROOT/project/work/doc/qc/sp
TODO_DIR=todo
FIXED_DIR=fixed
SIGNEDOFF_DIR=signedoff

echo >&2
echo ----------------------------------->&2
echo PHASE SPR Tracking System V00.03.02>&2
echo ShowSpr>&2
echo ----------------------------------->&2
echo >&2

umask 002
if test $1
then
   REL_NAME=$1
else
   echo "Usage: ShowSpr <VERSION> <NUMBER>"
   exit 1
fi

if test $2
then
   SPR_NUMBER=$2
   SPR_FILE_NAME=`echo -n "PHASE_"; echo $SPR_NUMBER | awk '{printf"%05d",$1}'`
else
   echo "Usage: ShowSpr <DATABASE> <NUMBER>"
   exit 1
fi

# check if the release directory exists
if test -d $REL_PATH/$REL_NAME
then
 
   FILE_NAME=`find $REL_PATH/$REL_NAME/todo -name $SPR_FILE_NAME -print`
   if test $FILE_NAME
   then
      echo "Version exists in todo directory "
      WHICH_DIR="todo"
   fi
 
   FILE_NAME=`find $REL_PATH/$REL_NAME/fixed -name $SPR_FILE_NAME -print`
   if test $FILE_NAME
   then
      echo "Version exists in fixed directory "
      WHICH_DIR="fixed"
   fi
 
   FILE_NAME=`find $REL_PATH/$REL_NAME/signedoff -name $SPR_FILE_NAME -print`
   if test $FILE_NAME
   then
      echo "Version exists in signedoff directory "
      WHICH_DIR="signedoff"
   fi
else
   echo "SPR tree for release $REL_NAME does not exist."
   echo "Exiting ShowSpr"
   exit 1
fi
 
cd $REL_PATH/$REL_NAME/$WHICH_DIR
 
cat $SPR_FILE_NAME

