#!/bin/sh 

REL_PATH=$PHASE_ROOT/project/work/doc/qc/sp
TODO_DIR=todo
FIXED_DIR=fixed
SIGNEDOFF_DIR=signedoff

echo 
echo -----------------------------------
echo PHASE SPR Tracking System V00.03.00
echo SignOffSpr
echo -----------------------------------
echo 

umask 002
if test $1
then
     REL_NAME=$1
else
     echo "Usage: SignoffSpr <VERSION>"
     exit 1
fi

# check if the release directory exists
if test -d $REL_PATH/$REL_NAME
then
        echo "FIXED SPRs..."
        cd $REL_PATH/$REL_NAME/$FIXED_DIR
        ls PHASE_*
        echo -n "Enter FIXED SPR name: ";read READ_SPR_FILE_NAME
        SPR_FILE_NAME=`echo $READ_SPR_FILE_NAME | awk '{printf($1)}' `

else
        echo SPR tree for release  $REL_NAME does not exist.
        echo "Exiting SignoffSpr";
        exit 1;
fi

FIXED_SPR=$SPR_FILE_NAME
SIGNEDOFF_SPR=$SPR_FILE_NAME

if test $SPR_FILE_NAME
then
   if test -f $FIXED_SPR
   then
      if test -f SCCS/p.$FIXED_SPR
      then
         echo Fixed SPR $SPR_FILE_NAME is being access by someone else
         exit 1;
      else
         sccs edit -s $FIXED_SPR
         sccs delta -s -y"Changing Status to Signed Off" $FIXED_SPR
      fi
   else
      echo Fixed SPR $SPR_FILE_NAME does not exist.
      exit 1;
   fi
else
   echo "No SPR specified"
   exit 1
fi

cd $REL_PATH/$REL_NAME/$SIGNEDOFF_DIR
sccs edit -s -r3 $FIXED_SPR

echo ""                                                                                >> $SIGNEDOFF_SPR
echo "------------------------------------------------------------------------------"  >> $SIGNEDOFF_SPR
echo ""                                                                                >> $SIGNEDOFF_SPR
echo "Signoff By          : "                                                       >> $SIGNEDOFF_SPR
echo ""                                                                                >> $SIGNEDOFF_SPR
echo -n "Date                : "                                                       >> $SIGNEDOFF_SPR
date '+%d/%m/%y : %H:%M' >> $SIGNEDOFF_SPR
echo ""                                                                                >> $SIGNEDOFF_SPR
echo "------------------------------------------------------------------------------"  >> $SIGNEDOFF_SPR

# edit the file
textedit $SIGNEDOFF_SPR

sccs delget -s -y"SignedOff" $SIGNEDOFF_SPR

# Cleanup
if test -f $SIGNEDOFF_SPR%
then
   rm $SIGNEDOFF_SPR%
fi
